Repository WebCrawlers-exe/DataStructure-Archives, pull requests merged in 2022-10, with the labels that each got.

#1 Added Stack Codes
  Stack/balancingExpressionUsingStack.cpp
  Stack/infixToPostfix.cpp
  Stack/postfixExpressionEvaluation.cpp
  Stack/stack.cpp
  Stack/stackImplementationUsingArray.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 Added leetcode solutions
  LeetCode Answers/1-two-sum/NOTES.md
  LeetCode Answers/1-two-sum/README.md
  LeetCode Answers/1. Array insert at end - GFG/1.-array-insert-at-end.cpp
  LeetCode Answers/1. Array insert at end - GFG/README.md
  LeetCode Answers/1. Count nodes of linked list - GFG/1.-count-nodes-of-linked-list.cpp
  LeetCode Answers/1. Count nodes of linked list - GFG/README.md
  LeetCode Answers/1. Implement Queue using array - GFG/1.-implement-queue-using-array.cpp
  LeetCode Answers/1. Implement Queue using array - GFG/README.md
  LeetCode Answers/1. Implement stack using array - GFG/1.-implement-stack-using-array.cpp
  LeetCode Answers/1. Implement stack using array - GFG/README.md
  LeetCode Answers/1. Inorder traversal of a BST - GFG/1.-inorder-traversal-of-a-bst.cpp
  LeetCode Answers/1. Inorder traversal of a BST - GFG/README.md
  LeetCode Answers/13. Next Greater Element - GFG/13.-next-greater-element.cpp
  LeetCode Answers/13. Next Greater Element - GFG/README.md
  LeetCode Answers/14-longest-common-prefix/README.md
  LeetCode Answers/19-remove-nth-node-from-end-of-list/19-remove-nth-node-from-end-of-list.cpp
  LeetCode Answers/19-remove-nth-node-from-end-of-list/NOTES.md
  LeetCode Answers/19-remove-nth-node-from-end-of-list/README.md
  LeetCode Answers/2. Array insert at index - GFG/2.-array-insert-at-index.cpp
  LeetCode Answers/2. Array insert at index - GFG/README.md
  LeetCode Answers/2. Linked List Insertion - GFG/2.-linked-list-insertion.cpp
  LeetCode Answers/2. Linked List Insertion - GFG/README.md
  LeetCode Answers/2. Operations on Queue - GFG/2.-operations-on-queue.cpp
  LeetCode Answers/2. Operations on Queue - GFG/README.md
  LeetCode Answers/20-valid-parentheses/20-valid-parentheses.cpp
  LeetCode Answers/20-valid-parentheses/NOTES.md
  LeetCode Answers/20-valid-parentheses/README.md
  LeetCode Answers/3-longest-substring-without-repeating-characters/3-longest-substring-without-repeating-characters.cpp
  LeetCode Answers/3-longest-substring-without-repeating-characters/NOTES.md
  LeetCode Answers/3-longest-substring-without-repeating-characters/README.md
  LeetCode Answers/3. Mean And Median of Array - GFG/3.-mean-and-median-of-array.cpp
  LeetCode Answers/3. Mean And Median of Array - GFG/README.md
  LeetCode Answers/3. Operations on Stack - GFG/3.-operations-on-stack.cpp
  LeetCode Answers/3. Operations on Stack - GFG/README.md
  LeetCode Answers/4. Queue Reversal - GFG/README.md
  LeetCode Answers/4. Removing consecutive duplicates - GFG/4.-removing-consecutive-duplicates.cpp
  LeetCode Answers/4. Removing consecutive duplicates - GFG/README.md
  LeetCode Answers/6. Kth largest element in a stream - GFG/6.-kth-largest-element-in-a-stream.cpp
  LeetCode Answers/6. Kth largest element in a stream - GFG/README.md
  LeetCode Answers/6. Parenthesis Checker - GFG/6.-parenthesis-checker.cpp
  LeetCode Answers/6. Parenthesis Checker - GFG/README.md
  LeetCode Answers/6. Strongest Neighbour - GFG/6.-strongest-neighbour.cpp
  LeetCode Answers/6. Strongest Neighbour - GFG/README.md
  LeetCode Answers/7. Implement two stacks in an array - GFG/7.-implement-two-stacks-in-an-array.cpp
  LeetCode Answers/7. Implement two stacks in an array - GFG/README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#9 Add files via upload
  Leetcode-main
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 added dining philosophers algorithm
  OS Algorithms/Dining philosophor.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#12 added semaphores
  OS Algorithms/semaphore.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 added the tangent algorithm code
  drone-path-planning-algo/main.py
  drone-path-planning-algo/t2.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#10 singly linked list added
  singly_linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 Remove Nth Node From End of List
  Linked List/Remove Nth Node From End of List.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#14 added roman to integer problem
  LeetCode Answers/13-Roman-to-integer/13-roman-to-integer.cpp
Labels: hacktoberfest, hacktoberfest2022

#16 Added buy and sell stock
  Stack/buySellStock.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#17 Insertion in BST
  Trees/insertionInBST.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 Create stock_span.cpp
  Stack/stock_span.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#19 added unique morse code problem
  LeetCode Answers/804-unique-morse-code/804-unique-morse-code.cpp
Labels: hacktoberfest2022

#20 added memoization problem
  LeetCode Answers/1155. Number of Dice Rolls With Target Sum/1155. Number of Dice Rolls With Target Sum.cpp
  LeetCode Answers/1155. Number of Dice Rolls With Target Sum/README.md
Labels: hacktoberfest2022

#21 added path sum
  LeetCode Answers/112-path-sum/112-path-sum.cpp
  LeetCode Answers/112-path-sum/README.md
Labels: hacktoberfest2022

#22 how to delete a node in double linked list
  double-linked-list.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 Split a Circular Linked List into two halves
  circular-linked-list.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 Count subarrays with same even and odd elements
  main.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#27 2nd PR
  test.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#28 3rd PR
  test.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#29 4th PR and 3rd PR fixed
  test.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
